### ISSUE TITLE
create UI for timeline files import and export 

### ISSUE THREAD

**Issue by jondhill333** [chingu-voyages/v18-geckos-team-02#105]

**Comment by lily-law** [comment]
![downloadIcon-flat.svg](https://images.zenhubusercontent.com/5e397fb29920ec321a6296ee/e9f58821-30ea-421d-9d24-864fb734fe1e)![uploadIcon-flat.svg](https://images.zenhubusercontent.com/5e397fb29920ec321a6296ee/33f173f6-50ee-4585-a170-6476061d7cd8)

Icons to use if you want them

Or for a less flat theme... 
![downloadIcon.svg](https://images.zenhubusercontent.com/5e397fb29920ec321a6296ee/9ed1fb32-683f-4a80-9abf-1e9564fa9a2a)![uploadIcon.svg](https://images.zenhubusercontent.com/5e397fb29920ec321a6296ee/169c343d-8b24-4528-93f0-6a61014dd6d1)


![addIcon.svg](https://images.zenhubusercontent.com/5e397fb29920ec321a6296ee/7d6de6c7-b316-4101-aedd-e50708841b01)



![add.svg](https://images.zenhubusercontent.com/5e8343b3d315a36401ed90da/f70d05c3-0d95-498a-9549-2e63a205f35f)
