### ISSUE TITLE
Research File Storage

### ISSUE THREAD

**Issue by jondhill333** [chingu-voyages/v18-geckos-team-02#2]
- [x] document google drive API basic setup and what it will require as an input and what to expect as output
- [x] look into what would work best as a simple local storage solution (local storage browser api, indexDB...)
    - list limitations (max file-size, storage space...)

**Comment by lily-law** [comment]
Google drive api
Expects: 
    - user access token
    - operation
        - files.list
            - returns: [file metadata](https://developers.google.com/drive/api/v3/reference/files) when input is a search operation
        - [file.get](https://developers.google.com/drive/api/v3/reference/files/get)
            - input: fileId
            - [extra options](https://developers.google.com/drive/api/v3/reference/files/get)
        - [files.create](https://developers.google.com/drive/api/v3/reference/files/create)

IndexedDB: 
- The maximum browser storage space is dynamic — it is based on your hard drive size. The global limit is calculated as 50% of free disk space.
- [Dexie](https://dexie.org/) - A Minimalistic Wrapper for IndexedDB

I made this diagram to help visualise how we might keep data in sync from client side to google drive
![localstorageleaddatadesign.png](https://images.zenhubusercontent.com/5e397fb29920ec321a6296ee/0e3232b5-a9fd-45dc-942e-10ee995a12db)
