### ISSUE TITLE
Design the file structure

### ISSUE THREAD

**Issue by jondhill333** [chingu-voyages/v18-geckos-team-02#8]

**Comment by lily-law** [comment]
# fileObj
``` 
{
    file: [uri/blob],
    timeStamps: {
        created: [dateTime],
        modified: [dateTime],
        user: [dateTime]
    },
    activeTimeStamp: [created/modified/user],
    tags: [Array]
}
```

# Needed operations/algorthms
- insert(fileObj)
- remove(fileObj)
- list({from, to})
- get(timeStamp)

# Data Structures
## Date Tree
```
{
    [yyyy]: {
        [mm]: {
            [dd]: {
                [hh]: {
                    [mm]: {
                        [ss]: [
                            [fileObj], [fileObj], [fileObj]
                        ]
                    }
                }
            }
        }
    }
}
```
### pros
- pre structured to suit our time line (year -> month -> date -> files)
- scoped 
### cons
- high insertion and even higher deletion cost
- requires a recursive cleanup after deleting a fileObj
- complex implimentation

## Buckets
```
{
    [yyyymmddhhss]: [fileObj]
}
```
### pros
- effiecent to insert, get, remove
- simple implementation
### cons
- will need more complex list function

## Sorted Array
```
[[fileObj]]
```
### pros
- simple
- list function is easy to implement
### cons
- requires sorting function after each insertion
- get and remove operations have high cost
