### ISSUE TITLE
create delete button

### ISSUE THREAD

**Issue by jondhill333** [chingu-voyages/v18-geckos-team-02#95]

**Comment by lily-law** [comment]
![trashIcon.svg](https://images.zenhubusercontent.com/5e397fb29920ec321a6296ee/109a2a29-d63f-4fc7-a460-f10e3e131d17)

**Comment by lily-law** [comment]
![dateAndTagsIcon.svg](https://images.zenhubusercontent.com/5e397fb29920ec321a6296ee/f6643058-ae24-45ed-b4aa-6a4c230e45a9)
